name: Deploy Angular to S3 & CloudFront

on:
  pull_request:
    types: [closed]
    branches:
      - master 

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Generate environment
        run: |
          mkdir -p src/environments
          echo "export const environment = {
            production: false
          };" > src/environments/environment.ts

      - name: Generate production environment
        run: |
          mkdir -p src/environments
          echo "export const environment = {
            production: true,
            apiUrl: '${{ secrets.API_URL }}'
          };" > src/environments/environment.prod.ts

      - name: Build Angular
        run: npm run build -- --configuration production

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Deploy to S3
        run: |
          aws s3 sync dist/frontend/browser/ s3://bfdna-front/ --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
